from templates.cot_prompt import *
from bs4 import BeautifulSoup

def parse_choice(answer: str) -> str:
    soup = BeautifulSoup(answer, "html.parser")
    

AGGREGATOR_PROMPT = """
You are an AI assistant solving a specific task. Your goal is to provide the most accurate and precise answer based on the task description.

Task Description:
{description}

## Solution

Some possible solutions have been generated by follows:
{solutions}

## Aggregator


"""